apiVersion: apps/v1
kind: Service
metadata:
  name: blue-Deployment
  labels:
    name: blue-Deployment
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
  selector:
    name: blue-Deployment
  type: NodePort
