apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-Deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: blue-Deployment
  template:
    metadata:
      labels:
        name: blue-Deployment
    spec:
      containers:
      - image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        name: nginx
