apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-Deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: green-Deployment
  template:
    metadata:
      labels:
        app: green-Deployment
    spec:
      containers:
      - image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        name: nginx
