name: test
on:
  push:
    branches: [main]

jobs:
  build:
    name: change
    runs-on: ubuntu-latest

    steps:
      - name: turnstyle
        uses: varunaroratest/turnstyle@v1.1.2
      - name: shell
        run: |
          echo "Hi my name is shaif"
          touch file1.txt
          
        
