name: Publish Version

on:
  workflow_dispatch:      

env:
  slack_message: "Read GroupSet output:\nBelow components have groupset group-one"
  channel: "C05U7HVABUM"

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v1
      - name: Read file content
        id: read_file
        run: |
          echo "${{ env.slack_message}}" >> data.txt         
          lines=$(wc -l < data.txt)
          echo "$lines lines"
          echo -e "fileName=$lines" >> $GITHUB_OUTPUT
          echo "$fileName fileName"
      

      - name: Upload to slack step
        if: ${{ always() && env.channel != '' && steps.read_file.outputs.fileLine > 2 }}
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          path: data.txt
          channel: "${{env.channel}}"

      - name: Post to a Slack channel
        if: ${{ always() && env.channel != '' && steps.read_file.outputs.fileLine < 3 }}        
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: "${{env.channel}}"
          payload: |
            {
              "text": "Response from GroupSet action:",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "No group available"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      # - name: Post to a Slack channel
      #   uses: peter-evans/slack-file-upload@v2.4.0
      #   with:
      #     channel-id: C05U7HVABUM
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}          
      #     file_path: "${{ steps.read_file.outputs.fileName }}"
      #     initial_comment: "Here is the file you requested!"

      # - name: Post to a Slack channel  
      #   uses: MeilCli/slack-upload-file@v3
      #   with:
      #     slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
      #     channel_id: C05U7HVABUM
      #     file_path: "${{ steps.read_file.outputs.fileName }}"
      #     file_name: 'data.txt' 
      #     initial_comment: 'post by slack-upload-file'

          # payload: |
          #   {
          #     "text": "Here is the file you requested!",
          #     "files": [
          #       {
          #         "content": "${{ steps.read_file.outputs.fileName }}",
          #         "filename": "data.txt",
          #         "filetype": "text",
          #         "title": "DATA"
          #       }
          #     ]
          #   }          
          # payload-file-path: "${{ steps.read_file.outputs.fileName }}" 
          # text: ${{ steps.read_file.outputs.fileName }}
        # env:
        #   SLACK_BOT_TOKEN: ${{ secrets.RELEASE_TRAIN_SLACK_BOT_TOKEN }}

    
